#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises'

const waiting = await readFile(new URL('../src/audio/task-waiting.wav', import.meta.url))
const completed = await readFile(new URL('../src/audio/task-completed.wav', import.meta.url))
const source = `/** Generated by scripts/embed-audio.mjs. Do not edit manually. */
export const NOTIFY_AUDIO = {
  waiting: '${waiting.toString('base64')}',
  completed: '${completed.toString('base64')}',
} as const
`
await writeFile(new URL('../src/audio/audio-data.ts', import.meta.url), source, 'utf8')
console.log('Embedded task-waiting.wav and task-completed.wav')
